### ISSUE TITLE
One error and lots of warnings in the latest Quicklisp version.

### ISSUE THREAD

**Issue by didierverna** [Shinmera/plump#15]
Hi,

I cannot load Plump anymore with the latest quicklisp version and the latest SBCL from git. See
[plump.log](https://github.com/Shinmera/plump/files/1431339/plump.log) for output (incidentally, this prevents me from loading els-web),

**Comment by Shinmera** [comment]
Can't reproduce this on SBCL 1.3.16. I'll try git HEAD.

**Comment by didierverna** [comment]
Or maybe not... I don't understand what's going on. It failed to load when I was trying to (asdf:load-system :els-web). However, doing (ql:quickload :plump) first seems to work.
Now, I get only some
[notes](https://github.com/Shinmera/plump/files/1431370/plump.log)

**Comment by Shinmera** [comment]
Loading with ASDF directly or Quickloading with verbose to T will turn warnings into errors. A "normal" Quickload will suppress them.

**Comment by didierverna** [comment]
I see. that must be it.

**Comment by Shinmera** [comment]
I fixed the warnings in 8b3a931.
