### ISSUE TITLE
 The type specifier (FUNCTION (STRING) BOOLEAN) cannot be used for discrimination.

### ISSUE THREAD

**Issue by franksmuc** [Shinmera/plump#17]
**++++ Error in (LISPWORKS:TOP-LEVEL-FORM 7): 
  The type specifier (FUNCTION (STRING) BOOLEAN) cannot be used for discrimination.

top level form 7 is 
(define-tag-dispatcher (process *xml-tags* *html-tags*) (name)
  (and (<= 1 (length name))
       (char= (aref name 0) #\?)))
in processing.lisp 
(using LispWorks 6.0.1)

**Comment by elrzn** [comment]
Cannot reproduce the issue on LispWorks 7.

**Comment by fiddlerwoaroof** [comment]
I reported this error to LW support and they patched it in Lispworks 7.1 or so

**Comment by Shinmera** [comment]
Cool, thanks!

**Comment by fiddlerwoaroof** [comment]
For reference, it's in 7.1.2 as documented here (Lisp Support Call #41557):

http://ftp.lispworks.com/pub/software_tools/downloads/patches/lw71/readme-712.txt
