### ISSUE TITLE
Will not compile via Quicklisp on LispWorks 7.1 Windows

### ISSUE THREAD

**Issue by hyphz** [Shinmera/plump#18]
Repeats the following error over and over:

**++++ Error between functions:
  Cannot read character U+0099 as part of a token because it has constituent trait 'invalid'.

**Comment by elrzn** [comment]
This was an issue with ASDF: https://bugs.launchpad.net/asdf/+bug/1766618

LispWorks users can either upgrade themselves to ASDF >3.3.2.7 or doing (pushnew :asdf-unicode *features*) before calling Quicklisp or ASDF.
