### ISSUE TITLE
cannot get elements with thead tag

### ISSUE THREAD

**Issue by shukryzablah** [Shinmera/plump#24]
The following code doesn't get me the vector of plump dom elements of type thead (returns NIL). However, If I change the tag to things like table, caption, or even tbody I do get the expected elements. 

Am I overlooking something here? I appreciate the help.

```lisp
(ql:quickload '("dexador" "plump"))
(defparameter *url* "https://en.wikipedia.org/wiki/Central_America")
(plump:get-elements-by-tag-name (plump:parse (dex:get *url*)) "thead")
```

**Comment by Shinmera** [comment]
Uh, there's just no thead elements in that document, so obviously it can't return any.

**Comment by shukryzablah** [comment]
You're right. I was checking with the inspector that comes in with my
browser and it must be adding those tags to the document.
