### ISSUE TITLE
[bug?] plump:serialize will not produce a forwardslash for tag "meta" 

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [Shinmera/plump#28]
I used the following snippet to reproduce the issue on my end:
```
(let ((root (plump:make-root)))
  (plump:set-attribute (plump:make-element root "meta")
                       "attri"
                       "1")
  (plump:serialize root)
  (format t "~%~%"))
```
And the output is as follows:
```
<meta attri="1">
```
There seems to be a forward slash missing. And the behavior is persistent if "meta" doesn't have any attributes.

This can be worked around with adding an additional text node with empty text, which will produce the following on `plump:serialize`:
```
<meta></meta>
```
It seems that this behavior only occur on tag "meta" so far.

**Comment by Shinmera** [comment]
This is how HTML requires things to work. You must set the `*tag-dispatchers*` to `*xml-tags*` if you want XML output.
