### ISSUE TITLE
Add HTML-specific parsing rules for nested tags

### ISSUE THREAD

**Issue by davidsun0** [Shinmera/plump#38]
Certain HTML tags like `<p>` [cannot be nested](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1):

> The P element represents a paragraph. It cannot contain block-level elements (including P itself).

It would be nice to add behavior to stop parsing and close nested tags immediately if a nested paragraph is detected.

Current behavior:
```
> (plump:serialize (plump:parse "<p>foo<p>bar"))
"<p>foo<p>bar</p></p>"
NIL
```

Expected behavior:
```
> (plump:serialize (plump:parse "<p>foo<p>bar"))
"<p>foo</p><p>bar</p>"
NIL
> (plump:serialize (plump:parse "<p>foo<span>bar<p>baz"))
"<p>foo<span>bar</span></p><p>baz</p>"
NIL
```

This is my quick and dirty solution which only works for paragraph tags. The actual rules for what tags are allowed where in the HTML5 spec is quite complicated. Maybe a full tag soup parser should be its own project?

```
(plump:define-tag-dispatcher (p-dispatcher plump:*tag-dispatchers*) (name)
  (string-equal name "p"))

(defvar *in-block* nil)

(plump:define-tag-parser p-dispatcher (name)
  (when *in-block*
    (plump:unread-n (1+ (length name)))
    (throw 'block nil))
  (let* ((closing (plump:consume))
	 (attributes (if (member closing plump-parser::*whitespace*)
			 (plump:read-attributes)
			 (plump:make-attribute-map)))
	 (plump:*root* (plump:make-element plump:*root* name
					   :attributes attributes))
	 (*in-block* t))
    (catch 'block
      (plump:read-children))
    plump:*root*))
```

**Comment by Shinmera** [comment]
I don't think we want to do this, at least not by default. I would not at all be surprised that there are documents out there that break this requirement on purpose and would then be parsed wrong.

**Comment by davidsun0** [comment]
Ok, that's reasonable. I'm parsing documents that don't close these tags. If I end up writing an entire tag soup parser, I'll probably release it as its own library.

**Comment by Shinmera** [comment]
There is cl-html5-parser that claims to be according to the html5 spec, though I have not used it extensively. It was also, back when plump was written, very slow in comparison. May or may not matter to you though or be accurate now.
