### ISSUE TITLE
Cloning root does not work

### ISSUE THREAD

**Issue by sirherrbatka** [Shinmera/plump#43]
(defclass root (nesting-node)
  ())

(:method ((node nesting-node) &optional (deep T))
    (let ((clone (make-instance (class-of node)
                                :parent (parent node)
                                :children (make-child-array))))
      (setf (children clone) (clone-children node deep clone))
      clone))

But the root, although is nesting-node, does not have parent. Therefore attempt to clone the root ends with an attempt to call the missing method.

**Comment by Shinmera** [comment]
Uh. Ok? Where are you seeing this code? Cause it's not in the plump source.

**Comment by sirherrbatka** [comment]
Yeah, it is not currently, but It used to be, and I am using shirakumako distribution which appears to have 1 year old version of plump in it.

**Comment by Shinmera** [comment]
Okey, dist should be updated now.
