### ISSUE TITLE
Spaces in attributes

### ISSUE THREAD

**Issue by ruricolist** [Shinmera/plump#5]
Spaces between attribute names, values, and equals signs are perfectly legal syntax for both HTML and XML:

```
<a href = "bar"></a>
```

But Plump mangles them:

```
(plump:serialize (plump:parse "<a href = \"bar\"></a>"))
=> <a ="" href="" "bar"=""/>
```

**Comment by Shinmera** [comment]
I'm quite embarrassed that this escaped me for so long. I'll get to a fix today, thanks for reporting.

**Comment by Shinmera** [comment]
Can you confirm the fix?

**Comment by ruricolist** [comment]
Fix confirmed.
